name: Check Style

on:
  workflow_dispatch:

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 24
      - name: Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Spotless
        run: ./gradlew spotlessCheck
